version: '3'

services:
  qdrant:
    image: qdrant/qdrant:latest
    ports:
      - "${QDRANT_PORT:-6333}:6333"
      - "${QDRANT_HTTP_PORT:-6334}:6334"
    volumes:
      - ./data:/qdrant/storage
    networks:
      - qdrant_network

  mcp-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${MCP_SERVER_PORT:-8000}:8000"
    environment:
      - QDRANT_URL=http://qdrant:6333
      - COLLECTION_NAME=${COLLECTION_NAME:-default-collection}
      - EMBEDDING_MODEL=${EMBEDDING_MODEL:-sentence-transformers/all-MiniLM-L6-v2}
    depends_on:
      - qdrant
    networks:
      - qdrant_network
    # デバッグ用：常にコンテナを再起動
    restart: on-failure
    # コンテナビルド時のログ出力を増やす
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  qdrant_network:
    driver: bridge
